# Generated by Django 4.2.4 on 2023-08-26 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_data',
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
